# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            CLUSTER
tagline:          'UNSUPERVISED ANALYSIS'
description:      'UNSUPERVISED ANALYSIS'
url:              https://cristianvergaraf.github.io/CristianVergaraFernandez_Portfolio/   # Update with your actual site URL
baseurl:          "/"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

